//
// Created by esaie on 24-07-20.
//

#ifndef GBA_SPRITE_ENGINE_PROJECT_RICHTING_H
#define GBA_SPRITE_ENGINE_PROJECT_RICHTING_H

enum class Richting {
    BOVEN,BENEDEN,LINKS,RECHTS
};

#endif //GBA_SPRITE_ENGINE_PROJECT_RICHTING_H
